In [1]:
import pandas as pd
import numpy as np

## 資料結構(Data structures)：Numpy arrays

### Series : 有 index 的一維陣列 (one-dimensional)
* 文件連結：
    * [pandas.Series](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.Series.html)
    * [Pandas 基礎教學](https://oranwind.org/python-pandas-ji-chu-jiao-xue/)

In [2]:
# 建立一個 series
# 預設的 index 為 數值 且 從 0 開始
s1 = pd.Series([1., 2., 3.])
print(s1)
print()
print(type(s1))
print()
# 在 series 後加上 .values 屬性(attributes)，回傳 ndarray-like (numpy.array)
print(s1.values)
print(type(s1.values))

print('=====================')

# 建立一個 series，自訂 index 為 文字
s2 = pd.Series([1., 2., 3.], index=['a', 'b', 'c'])
print(s2)
print()
print(type(s2))
print()
# 在 series 後加上 .values 屬性(attributes)，回傳 ndarray-like (numpy.array)
print(s2.values)
print(type(s2.values))

print('=====================')

# 建立一個 series，自訂 index 為 datetime(利用 pandas.date_range，freq 為 Hour)
s3 = pd.Series([1., 2., 3.], index=pd.date_range('2018-01-01', periods=3, freq='H'))
print(s3)
print()
print(type(s3))
print()
# 在 series 後加上 .values 屬性(attributes)，回傳 ndarray-like (numpy.array)
print(s3.values)
print(type(s3.values))

0    1.0
1    2.0
2    3.0
dtype: float64

<class 'pandas.core.series.Series'>

[1. 2. 3.]
<class 'numpy.ndarray'>
a    1.0
b    2.0
c    3.0
dtype: float64

<class 'pandas.core.series.Series'>

[1. 2. 3.]
<class 'numpy.ndarray'>
2018-01-01 00:00:00    1.0
2018-01-01 01:00:00    2.0
2018-01-01 02:00:00    3.0
Freq: H, dtype: float64

<class 'pandas.core.series.Series'>

[1. 2. 3.]
<class 'numpy.ndarray'>


In [3]:
# 觀察 3.1 boolean index 中 所使用的 boolean vector 其資料格式為 series
print(type(boolean_vector))
print()
# 在 series 後加上 .values 屬性(attributes)，回傳 ndarray-like (numpy.array)
print(boolean_vector.values)
print(type(boolean_vector.values))

NameError: name 'boolean_vector' is not defined

### numpy.array : 陣列，array 之中的每一個元素都必須是相同型態
* 文件連結：[numpy.array](https://docs.scipy.org/doc/numpy-1.14.0/reference/generated/numpy.array.html)

In [11]:
# 建立一個 array
arr = np.array([1,2,3])
print(arr)
print(type(arr))

print('=====================')

# boolean vertor 的用法在 array 上一樣可以使用
print(arr != 2)
print(arr[arr != 2])

[1 2 3]
<class 'numpy.ndarray'>
[ True False  True]
[1 3]
